<a href="https://colab.research.google.com/github/Zabiullahkhan/Data_Science/blob/main/Krish_Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 511.7 MB 6.7 kB/s 
     |████████████████████████████████| 438 kB 72.3 MB/s 
     |████████████████████████████████| 1.6 MB 59.8 MB/s 
     |████████████████████████████████| 5.8 MB 59.8 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [11]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[409, 114, 276, 20], [409, 114, 276, 231], [409, 402, 276, 256], [420, 91, 230, 349, 49], [420, 91, 230, 349, 308], [135, 409, 282, 276, 79], [77, 16, 147, 349]]


### Word Embedding Represntation

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 409 114 276  20]
 [  0   0   0   0 409 114 276 231]
 [  0   0   0   0 409 402 276 256]
 [  0   0   0 420  91 230 349  49]
 [  0   0   0 420  91 230 349 308]
 [  0   0   0 135 409 282 276  79]
 [  0   0   0   0  77  16 147 349]]


In [15]:
## 10 feature dimesnions
dim=10


In [16]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 409, 114, 276,  20], dtype=int32)

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 66ms/step


array([[ 0.01347432, -0.0368381 ,  0.0094584 , -0.03862176,  0.00990032,
        -0.03344071,  0.04675673, -0.0351199 ,  0.03503721, -0.01308434],
       [ 0.01347432, -0.0368381 ,  0.0094584 , -0.03862176,  0.00990032,
        -0.03344071,  0.04675673, -0.0351199 ,  0.03503721, -0.01308434],
       [ 0.01347432, -0.0368381 ,  0.0094584 , -0.03862176,  0.00990032,
        -0.03344071,  0.04675673, -0.0351199 ,  0.03503721, -0.01308434],
       [ 0.01347432, -0.0368381 ,  0.0094584 , -0.03862176,  0.00990032,
        -0.03344071,  0.04675673, -0.0351199 ,  0.03503721, -0.01308434],
       [ 0.02409439, -0.02612332, -0.01115816, -0.02842011,  0.03316906,
        -0.00617754,  0.02990259,  0.02108777,  0.00960201, -0.0171253 ],
       [-0.00515671,  0.03469114, -0.02467139,  0.01143644,  0.02854215,
        -0.04275519,  0.03389775,  0.02689738,  0.03797367,  0.03112701],
       [ 0.01680266, -0.0276046 ,  0.02754101, -0.01705457, -0.01789315,
        -0.0095524 , -0.02579536,  0.00432745

In [20]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 29ms/step
[[[ 1.3474319e-02 -3.6838103e-02  9.4584003e-03 -3.8621761e-02
    9.9003203e-03 -3.3440709e-02  4.6756733e-02 -3.5119902e-02
    3.5037208e-02 -1.3084341e-02]
  [ 1.3474319e-02 -3.6838103e-02  9.4584003e-03 -3.8621761e-02
    9.9003203e-03 -3.3440709e-02  4.6756733e-02 -3.5119902e-02
    3.5037208e-02 -1.3084341e-02]
  [ 1.3474319e-02 -3.6838103e-02  9.4584003e-03 -3.8621761e-02
    9.9003203e-03 -3.3440709e-02  4.6756733e-02 -3.5119902e-02
    3.5037208e-02 -1.3084341e-02]
  [ 1.3474319e-02 -3.6838103e-02  9.4584003e-03 -3.8621761e-02
    9.9003203e-03 -3.3440709e-02  4.6756733e-02 -3.5119902e-02
    3.5037208e-02 -1.3084341e-02]
  [ 2.4094392e-02 -2.6123321e-02 -1.1158157e-02 -2.8420115e-02
    3.3169065e-02 -6.1775446e-03  2.9902589e-02  2.1087769e-02
    9.6020103e-03 -1.7125297e-02]
  [-5.1567070e-03  3.4691144e-02 -2.4671389e-02  1.1436440e-02
    2.8542150e-02 -4.2755187e-02  3.3897746e-02  2.6897382e-02
    3.7973668e-02  3.1

In [21]:
embedded_docs[0]

array([  0,   0,   0,   0, 409, 114, 276,  20], dtype=int32)

In [22]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 14ms/step
[[ 0.01347432 -0.0368381   0.0094584  -0.03862176  0.00990032 -0.03344071
   0.04675673 -0.0351199   0.03503721 -0.01308434]
 [ 0.01347432 -0.0368381   0.0094584  -0.03862176  0.00990032 -0.03344071
   0.04675673 -0.0351199   0.03503721 -0.01308434]
 [ 0.01347432 -0.0368381   0.0094584  -0.03862176  0.00990032 -0.03344071
   0.04675673 -0.0351199   0.03503721 -0.01308434]
 [ 0.01347432 -0.0368381   0.0094584  -0.03862176  0.00990032 -0.03344071
   0.04675673 -0.0351199   0.03503721 -0.01308434]
 [ 0.02409439 -0.02612332 -0.01115816 -0.02842011  0.03316906 -0.00617754
   0.02990259  0.02108777  0.00960201 -0.0171253 ]
 [-0.00515671  0.03469114 -0.02467139  0.01143644  0.02854215 -0.04275519
   0.03389775  0.02689738  0.03797367  0.03112701]
 [ 0.01680266 -0.0276046   0.02754101 -0.01705457 -0.01789315 -0.0095524
  -0.02579536  0.00432745  0.04485713  0.04820336]
 [ 0.01776372  0.01075314 -0.01567445  0.04915084 -0.02862983 -0.00393905


In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]