<a href="https://colab.research.google.com/github/Zabiullahkhan/Data_Science/blob/main/NumPy_Cheat_Sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Cheat Sheet
NumPy provides tools for working with arrays. All of the
following code examples refer to the arrays below.

 ImportNumPy 

In [1]:
import numpy as np

Create Arrays:

In [ ]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3),(4,5,6)],[]])

Initial placeholders:

In [ ]:
np.zeros((3,4)) #Create an array of zeros
np.ones((2,3,4),dtype=np.int16)
d = np.arange(10,25,5)
np.linspace( 0,2, 9)
e = np.full((2,2), 7)
f = np.eye(2)
np.random.random((2,2))
np.empty((3,2))

Saving & Loading On Disk:

In [ ]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

Saving & Loading Text Files

In [ ]:
np.loadtxt('my_file.txt')
np.genfromtxt('my_file.csv',
delimiter=',')
np.savetxt('myarray.txt', a,
delimiter= ' ')

Inspecting Your Array

In [ ]:
a.shape
len(a)
b.ndim
e.size
b.dtype #data type
b.dtype.name
b.astype(int) #change data type

Data Types

In [ ]:
np.int64
np.float32
np.complex
np.bool
np.object
np.string_
np.unicode_

Array Mathematics

Arithmetic Operations

In [ ]:
g = a-b
array([[-0.5, 0. , 0. ],
[-3. , 3. , 3. ]])
np.subtract(a,b)
b+a
array([[2.5, 4. , 6. ],
[ 5. , 7. , 9. ]])
np.add(b,a)
a/b
array([[ 0.66666667, 1. , 1. ],
[ 0.2 5 , 0.4 , 0 . 5 ]])
np.divide(a,b)
a*b
array([[ 1 . 5, 4. , 9. ],
[ 4. , 10. , 18. ]])
np.multiply(a,b)
np.exp(b)
np.sqrt(b)
np.sin(a)
np.log(a)
e.dot(f)

Aggregate functions:

In [ ]:
a.sum()
a.min()
b.max(axis= 0)
b.cumsum(axis= 1) #Cumulative sum
a.mean()
b.median()
a.corrcoef() #Correlation coefficient
np.std(b) #Standard deviation

Copying arrays:

In [ ]:
h = a.view() #Create a view
np.copy(a)
h = a.copy() #Create a deep copy

Sorting arrays:

In [ ]:
a.sort() #Sort an array
c.sort(axis=0)

# Array Manipulation

Transposing Array:

In [ ]:
i = np.transpose(b)
i.T

Changing Array Shape:

In [ ]:
b.ravel()
g.reshape(3,-2)

Adding/removing elements:

In [ ]:
h.resize((2,6))
np.append(h,g)
np.insert(a, 1, 5)
np.delete(a,[1])

Combining arrays:

In [ ]:
np.concatenate((a,d),axis=0)
np.vstack((a,b)) #stack vertically
np.hstack((e,f)) #stack horizontally

Splitting arrays:

In [ ]:
np.hsplit(a,3) #Split horizontally
np.vsplit(c,2) #Split vertically

Subsetting

In [ ]:
b[1,2]

Slicing:

In [ ]:
a[0:2]

Boolean Indexing:

In [ ]:
a[a<2]